language: nix

# Do not spam me with build status emails.
notifications:
  email: false

cache:
  directories:
    - $TRAVIS_HOME/.cargo/
    - target
    - app/.psc-package

addons:
  apt:
    packages:
    - libasound2-dev

before_install:
  # Make the pinned build environment available on the PATH.
  - export PATH=$(nix-build --no-out-link)/bin:$PATH

install:
  # Trigger Rustup to download and install the Rust toolchain.
  - cargo --version

  # Install libsystemd, because we want to link against the system one,
  # not the one from Nixpkgs.
  - sudo apt install libsystemd-dev

script:
  - cargo build
  - cargo test
  - make -C app
  - mkdocs build

before_cache:
  - rm -fr "$TRAVIS_HOME/.cargo/registry/src"
