site_name: Musium
site_url: https://docs.ruuda.nl/musium/
repo_url: https://github.com/ruuda/musium
strict: true

theme:
  name: null
  custom_dir: docs/theme

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: null

nav:
  - Overview: index.md
  - User Guide:
    - Building: building.md
    - Configuration: configuration.md
    - Running: running.md
    - Webinterface: webinterface.md
    - Tagging: tagging.md
    - Loudness normalization: loudness.md
    - High-pass filter: highpass.md
    - Rating: rating.md
    - Scrobbling to Last.fm: scrobbling.md
    - Submitting to Listenbrainz: listenbrainz.md
    - Importing from Last.fm: lastfm-import.md
    - Trådfri control: tradfri.md
    - Disks: disks.md
    - Changelog: changelog.md
  - API Reference: api.md
  - Internals:
    - Playcounts: playcounts.md
    - Search: search.md
    - Performance: performance.md
    - Thumbnails: thumbnails.md
